//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nerdz.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nerdz.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;app&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;body&quot;&gt;
        ///        &lt;div id=&quot;left&quot;&gt;
        ///            &lt;ul id=&quot;conversations&quot;&gt;&lt;/ul&gt;
        ///        &lt;/div&gt;
        ///        &lt;div id=&quot;center&quot;&gt;
        ///            &lt;ul id=&quot;conversation&quot;&gt;&lt;/ul&gt;
        ///            &lt;div id=&quot;form&quot;&gt;
        ///                &lt;textarea id=&quot;textarea&quot;&gt;&lt;/textarea&gt;
        ///                &lt;button id=&quot;send&quot; name=&quot;send&quot; onclick=&quot;external.Send(window.otherUsername, document.getElementById(&apos;textarea&apos;).value)&quot;&gt;Send&lt;/button&gt;
        ///            &lt;/div&gt;
        ///        &lt;/div&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string app {
            get {
                return ResourceManager.GetString("app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #left {
        ///    width: 25%;
        ///    float: left;
        ///    height: 100%;
        ///}
        ///
        ///#center {
        ///    border-left: 2px solid black;
        ///    width: 74%;
        ///    float: left;
        ///    height: 100%;
        ///}
        ///
        ///#body {
        ///    overflow: hidden;
        ///    clear: both;
        ///    height: 100%;
        ///}
        ///
        ///#form {
        ///    display: none;
        ///}
        ///
        ///.messageLeft {
        ///    float: left;
        ///}
        ///
        ///.messageRight {
        ///    float: right;
        ///}
        ///
        ///body {
        ///    height: 100%;
        ///}.
        /// </summary>
        internal static string css {
            get {
                return ResourceManager.GetString("css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var getConversation = function (index, options) {
        ///    options = options ? options : { &quot;from&quot;: 0, &quot;howMany&quot;: 10 };
        ///    external.Conversation(index, options.from, options.howMany);
        ///};
        ///
        ///var appendConversation = function (ol, username, date, index) {
        ///    var li = document.createElement(&quot;li&quot;);
        ///    var text = document.createTextNode(username);
        ///    li.onclick = function () {
        ///        window.otherUsername = username;
        ///        getConversation(index);
        ///    };
        ///    li.appendChild(text);
        ///    ol.appendChild(li) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string js {
            get {
                return ResourceManager.GetString("js", resourceCulture);
            }
        }
    }
}
